### PR TITLE
Randomized sorting of cards

### PR DESCRIPTION
**Pull request by gopkumr**
Addresses #47 
Please review the way I have implemented the random sorting of the list of projects. 

Random sorting happens only when there are no filters, in the case when a user puts in a filter, he will always see the same result in the same order.

### CODE REVIEW

**Comment by sara-02** [comment]
@gopkumr Can you test it locally and share a screenshot? Rest looks good.

**Comment by gopkumr** [comment]
@sara-02 I am attaching a GIF animation of the random sorting of cards.

Issue47Fix

**Comment by sara-02** [comment]
@gopkumr Thanks, this is great!

**Comment by jancborchardt** [comment]
Nice, looking good! :) Seems it still needs to be deployed to https://firstcontributions.github.io – is that a different branch?

**Pull request merged**
