### PR TITLE
added support for other code hosting platforms #102

### PR DESCRIPTION
**Pull request by NdibeRaymond**
changed "githubLink" to "projectLink" in the "listofprojects.js" file as well as components that depends on the file.
i ran it locally and confirmed that my changes didn't break anything before submitting this PR
**Fixes** #102

### CODE REVIEW

**Comment by sara-02** [comment]
@NdibeRaymond Can you show us a screenshot of the site run locally. Just to make sure things are working fine.

**Comment by NdibeRaymond** [comment]
@sara-02 here
first-contributions
first-contributions_1

**Comment by NdibeRaymond** [comment]
It was auto generated. Looking at the file, it looks likes it was generated when yarn install failed due to connectivity problem. Should have added it to fit ignore or deleted it entirely

**Comment by sara-02** [comment]
@NdibeRaymond Can you please remove it from this PR, and add it to .gitignore instead.

**Comment by NdibeRaymond** [comment]
Done

**Comment by sara-02** [comment]
LGTM @Roshanjossey PTAL at this and merge it.

**Comment by Roshanjossey** [comment]
Merging it

**Pull request merged**
