### PR TITLE
Fix align items mismatched css property

### PR DESCRIPTION
**Pull request by ahmadshalabi**
Addresses #107

### CODE REVIEW

**Comment by ahmadshalabi** [comment]
@sara-02  @Roshanjossey 
Could you please review?

**Comment by sara-02** [comment]
@ahmadshalabi Can you please update this PR based on the latest PR that got merged.

**Comment by ahmadshalabi** [comment]
> @ahmadshalabi Can you please update this PR based on the latest PR that got merged.

I think it already based on the latest PR that got merged. If not, Can you please provide more information about how I can do it?

**Comment by sara-02** [comment]
https://gist.github.com/santisbon/a1a60db1fb8eecd1beeacd986ae5d3ca

**Comment by ahmadshalabi** [comment]
@sara-02, 
I will close this PR in favor of PR #109 Please check it.
Thanks

**Pull request closed without merging**
