### PR TITLE
Update App.jsx from class component to functional component

### PR DESCRIPTION
**Pull request by gabrielsanttana**
## What:

Update App.jsx from class component to functional component.

## Why:

Class components are a bit deprecated, since they're not able to use hooks and other recent features of React. 

## How:

Updated the `App.jsx` file to be a functional component.

### CODE REVIEW

**Comment by gabrielsanttana** [comment]
Hey, @Roshanjossey, could you take a look at this one for me, please?

**Comment by gabrielsanttana** [comment]
Hey, @sara-02, could you take a look at this one for me, please?

**Comment by Roshanjossey** [comment]
Thank you for making this change @gabrielsanttana. Sorry that I didn't merge it earlier.

**Comment by gabrielsanttana** [comment]
> Thank you for making this change @gabrielsanttana. Sorry that I didn't merge it earlier.

It's alright, @Roshanjossey. I should have asked you again before. Thanks!

**Pull request merged**
