### PR TITLE
Changes on header section and card's button

### PR DESCRIPTION
**Pull request by Muhammed-Rahif**
###  **@sara-02  Here is a preview of what I did...!**

1. First change :-
FirstContributionsPreview

2. Second change :-
FirstContributionsPreview2

### CODE REVIEW

**Comment by aryasoni98** [comment]
@Muhammed-Rahif nice animation and project card 👍🏻

**Comment by Muhammed-Rahif** [comment]
@aryasoni98 Thank you... 🤩️

**Comment by Roshanjossey** [comment]
Good job @Muhammed-Rahif. I like the changes.

**Comment by Muhammed-Rahif** [comment]
> Good job @Muhammed-Rahif. I like the changes.

Thank you....🤩️

**Pull request merged**
