### PR TITLE
Add Scribe-Android to listOfProjects.js

### PR DESCRIPTION
**Pull request by andrewtavis**
Hey @Roshanjossey 👋

Sending along the Android version of the iOS app Scribe - Language Keyboard, which is already on here. The [Scribe](https://github.com/scribe-org) community is a [Wikimedia project for new developers](https://www.mediawiki.org/wiki/New_Developers#Scribe) that's been growing recently :) We have tons of [good first issues](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) now for the Android app, and it'd be great if we could get your all's support with contributor acquisition! This PR also updates the Scribe-iOS entry so the projects are distinct 😊

Note that we're currently working on an MVP for Scribe-Android right now, so it's totally fine if you'd prefer me to send this along when we've finished the first release. Also let me know if you'd prefer me to just combine the entries and add an Android and Kotlin tag to the existing entry :)

Hope all's well with you! 😊

### CODE REVIEW

**Comment by ekrishnachaitanya2004** [comment]
I would like to extend an invitation to individuals interested in contributing to my open-source website. Your participation and contributions will be greatly appreciated.
[**Link**](https://github.com/Snakes-n-Networks/Dev-blogs.git)

**Comment by andrewtavis** [comment]
Thanks so much for the continued support, @Roshanjossey! 😊😊

Hope all's well :)

**Comment by Roshanjossey** [comment]
All is well.

I haven't been able to give much attention to firstcontributions.github.io recently. Gotta go through those PRs.

How are you? Do you visit any hackspaces in Berlin?

**Comment by andrewtavis** [comment]
Take your time with the PRs :) 

Generally good! Happy that the respective projects are still going and work and life are also good. Lots to do, but I'm learning more how to manage things :) 

I do sometimes go to hacker spaces in Berlin. c-base for things like Berlin Hack & Tell, and I've been meaning to check out xHain. I'm also at a few meetups like the Vue one and sometimes the Swift one. 

Also will be at Chaos Communication Congress in Hamburg in a few weeks :) 

Are you Berlin based?

**Comment by Roshanjossey** [comment]
cool cool cool

I've been to c-base for NixOS Stammtisch. I wasn't using Nix then so I was asking questions and checking out what they were building.

Have fun in Hamburg 🙌 

I travel to Berlin every month and work from the office there for a week.

**Comment by andrewtavis** [comment]
Nice! Let me know if you're ever off to a hackspace in Berlin when you're here and maybe it can work out that we meet up! 😊

**Comment by Roshanjossey** [comment]
Hi @andrewtavis, I'll be in Berlin next week. let me know if you're going to some meetup :)

**Comment by andrewtavis** [comment]
I'm not seeing anything in the calendar, but happy to meet for a coffee if you'd like! Feel free to reach out at the email that's in my profile 😊

**Pull request merged**
