### PR TITLE
Add activist to listOfProjects.js

### PR DESCRIPTION
**Pull request by andrewtavis**
Hey there! Just open-sourced a new project and am hoping to get it on here like another one of mine 😊 Let me know if there's anything else I need to do!

### CODE REVIEW

**Comment by andrewtavis** [comment]
@Roshanjossey, would you be able to give me some feedback on whether this project works for firstcontributions? :) Thanks and hope you're well!

**Comment by andrewtavis** [comment]
@Roshanjossey, checking in with you again, which I hope is ok :) We're in the midst of creating new issues at the moment and are growing the team/contributors 😊🚀 Would be great if we could add the firstcontributions bump to our efforts to grow our community!

**Comment by Roshanjossey** [comment]
Hi @andrewtavis, sorry for not responding earlier.

I went through activist repo and it looks really good. I'm sure it would grow into a thriving community that brings about big changes in the world.

**Comment by andrewtavis** [comment]
Thank you, @Roshanjossey!! Really grateful to have your all's support 🙏 Wishing you the best!

**Pull request merged**
