### PR TITLE
Changed links to contribute

### PR DESCRIPTION
**Pull request by isa3bel**

### CODE REVIEW

**Comment by isa3bel** [comment]
Hello @sara-02, it seems that when I click on the project links, it still doesn't navigate to the contribute page. Do you know why this is? The branch was merged, so I should be seeing the changes correct?

**Comment by sara-02** [comment]
Hey isa3bel, we have not been able to the roll out the changes. Once that happens, the updated master will be picked and your chances will reflect online.

**Comment by tiferet** [comment]
@sara-02 This still doesn't seem to have been resolved. Is that to be expected?

**Comment by sara-02** [comment]
@tiferet I do not have access to roll out changes.
@Roshanjossey Can you look into it.

**Comment by gavv** [comment]
This probably should be reverted.

For all or almost all projects the `/contribute` link shows different set of tasks, compared to the original link. The reason is that each project has its own tags for contributors, which was reflected by the github links before this PR.

See #73.

**Comment by Roshanjossey** [comment]
The latest changes are deployed now

**Comment by Roshanjossey** [comment]
@gavv, thank you for pointing out that this change might now be what we really need. I'm not sure at the moment. I've not read much about `/contribute` link and I'm yet to form an opinion.

@sara-02 , @tiferet , can we have a discussion about it?

**Pull request merged**
